sudo: required
services:
  - docker

before_install:
  - docker build -t gummadille010/docker-react -f Dockerfile.dev .
  
script:
  - docker run gummadille010/docker-react npm run test -- --coverage